version: '3.8'

services:
  user-service:
    build:
      context: .  # Path to the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 on the host
    environment:
      MONGODB_URI: mongodb://mongo:27017/user-service # MongoDB connection string
      JWT_SECRET: 23961c1ac9c921d5fed2901b75dbb6e007242660d912958000d440c4a291cbee  # Replace with your secret
      PORT: 5000
    depends_on:
      - mongo  # Wait for the MongoDB service to start

  mongo:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Map port 27017 of the container to port 27017 on the host
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:  # Named volume for MongoDB data persistence